---
title: "06 File Formats"
---

# File Formats {-}

For every research project, it's important to consider which file formats you'll use to save and store your data and files.  In some instances, the file formats you use will be dictated by software, instruments, or other factors in your research project or field, but in other cases, you may have the option to choose between several different formats. The type of data that you're working with will also play a factor in determining the file formats you use, but considering your workflows and project goals should play a large role in selecting formats. 

## File Format Best Practices {-}

* If possible, collect data in open and non-proprietary formats 
* If not possible to collect open / non-proprietary formats, try to pick a format that can be easily converted to an open format
* Consider software and formats that are widely used within your discipline
* Be aware of software, hardware, and licensing requirements for viewing and working with data
* Be aware of using elements such as colour or highlighting as a form of metadata, as they may be lost if converted to a different format

### File Formats and Data Types {-}

* Raw
* In process
* For deposit

### Manuscrips {-}

### Documentation files {-}

## Questions {-}

What file formats will be used for what content types?