---
title: "10 Offboarding"
---

# Offboarding {-}

Offboarding is a systematic process to ensure that when people leave your team you have all the information you require to continue your research in an orderly and smooth fashion.

The longer the amount of time your research project operates, the more likely that you will have people, such as students at various levels, join and leave the research team. Having a standard process for offboarding people will prevent or reduce:

* People leaving and taking needed passwords and/or files with them.
* Time lost locating files required for continued work.
* Possible file security breaches in the future.

This is especially helpful when working with a group or sharing data with others. Concretely outlining the steps everyone must take before they complete their term is good practice.

## General Rules {-}

An offboarding guide should contain:

* Any already existing administrative requirements for offboarding such as returning keys, and expiring accounts to specific computer drives or storage locations. Avoid duplicating procedures that already exist and that are sufficient for your purposes.
* Ensure the offboarding process be completed by every person prior to ending their term on your research project or in your research lab.
* All offboarding documents should be reviewed by either the lab manager, the PI, or their designate at least 5 days in advance of the final working day of the person leaving.
* Be written as plain text.
* Contain a checklist of actions specific to your research, including but not limited to
    1.  Locations of all files worked on that are pertinent to the project and any passwords created by this person to secure those files.
    2.  Are files accessible by other members of the team
    3.  Specific feedback about the research project that might be useful to your team or lab in the future.
    4.  Recommmendations from the person leaving about any processes or procedures that were good, that did not work, or that were outdated.
    5.  Future contact information, if needed.

## Roles and Responsibilities {-}

It's important to remember that having a documentation system that your team can easily update throughout a project is more benefical than one that begins with great detail, but is difficult to maintain.  As the project grows and new files and folders are created, clearly identifying what information team members need to document, and where that information needs to be put, will help keep things on track.  It is also worth considering having a person who periodically will check the documentation to ensure that it's accurate, and can update any inconsistencies. The offboarding documents can be a valuable source of information to assist in keeping the documentation system up to date.